name: ns_firebase_utils
description: This package provides a comprehensive set of methods and extensions for Firebase, simplifying its integration into your Flutter projects while also adding valuable functionality.
version: 1.1.3
homepage: https://github.com/ProjectAJ14/ns_firebase_utils

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.9.2
  cloud_functions: ^4.4.1
  fake_cloud_firestore: ^2.4.1+1
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_dynamic_links: ^5.3.6
  firebase_messaging: ^14.6.8
  firebase_remote_config: ^4.2.6
  firebase_storage: ^11.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
