name: ns_firebase_utils
description: This package provides a comprehensive set of methods and extensions for Firebase, simplifying its integration into your Flutter projects while also adding valuable functionality.
version: 1.1.4
homepage: https://github.com/ProjectAJ14/ns_firebase_utils

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  fake_cloud_firestore: ^3.0.1
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_dynamic_links: ^6.0.2
  firebase_messaging: ^15.0.2
  firebase_remote_config: ^5.0.2
  firebase_storage: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
