name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 1.1.1
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.2.0
  cloud_functions: ^4.0.6
  fake_cloud_firestore: ^2.1.0
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_dynamic_links: ^5.0.9
  firebase_messaging: ^14.1.4
  firebase_remote_config: ^3.0.7
  firebase_storage: ^11.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
