name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 1.1.0
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  firebase_storage: ^10.3.2
  cloud_firestore: ^3.3.0
  cloud_functions: ^3.3.2
  firestore_ui: ^1.23.0
  firebase_analytics: ^9.2.0
  firebase_crashlytics: ^2.8.5
  firebase_dynamic_links: ^4.3.2
  firebase_remote_config: ^2.0.12
  firebase_messaging: ^12.0.0
  fake_cloud_firestore: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
