name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 1.0.0-nullsafety
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #<editor-fold desc="FIREBASE">
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  firebase_storage: ^10.0.5
  cloud_firestore: ^1.0.7
  cloud_functions: ^3.0.4
  firestore_ui: ^1.20.0
  firebase_analytics: ^8.3.3
  firebase_crashlytics: ^2.2.3
  firebase_dynamic_links: ^2.0.10
  firebase_remote_config: ^0.11.0+1
  firebase_performance: ^0.7.1+4
  firebase_messaging: ^10.0.8
  #</editor-fold>

  #<editor-fold desc="FIREBASE TEST">
  cloud_firestore_mocks: ^0.8.4
  #</editor-fold>


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
