name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 1.1.2
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.9.1
  cloud_functions: ^4.4.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_dynamic_links: ^5.3.5
  firebase_messaging: ^14.6.7
  firebase_remote_config: ^4.2.5
  firebase_storage: ^11.2.6
  cloud_firestore_platform_interface: ^5.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
