name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 1.0.0-nullsafety
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #<editor-fold desc="FIREBASE">
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  cloud_firestore: ^2.1.0
  cloud_functions: ^3.2.5
  firestore_ui: ^1.20.0
  firebase_analytics: ^9.0.5
  firebase_crashlytics: ^2.4.5
  firebase_dynamic_links: ^4.0.4
  firebase_remote_config: ^2.0.0
  firebase_messaging: ^11.2.5
  #</editor-fold>

  #<editor-fold desc="FIREBASE TEST">
  cloud_firestore_mocks: ^0.9.0+1
  #</editor-fold>


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
