name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 1.0.0-nullsafety
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  firebase_storage: ^10.3.1
  cloud_firestore: ^3.2.1
  cloud_functions: ^3.3.1
  firestore_ui: ^1.23.0
  firebase_analytics: ^9.1.12
  firebase_crashlytics: ^2.8.4
  firebase_dynamic_links: ^4.3.1
  firebase_remote_config: ^2.0.11
  firebase_messaging: ^11.4.4


  fake_cloud_firestore: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
