name: ns_firebase_utils
description: Set of methods/extentions for firebase that makes using framework in a much easier and clean way also adds additional functionality
version: 1.1.0
homepage: https://github.com/ajaynonstopio/ns_firebase_utils

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_storage: ^10.3.4
  cloud_firestore: ^3.4.3
  cloud_functions: ^3.3.3
  firestore_ui: ^1.24.0
  firebase_analytics: ^9.3.0
  firebase_crashlytics: ^2.8.6
  firebase_dynamic_links: ^4.3.3
  firebase_remote_config: ^2.0.13
  firebase_messaging: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
